import * as React from 'react';
import { useObserveHook } from '@/hook';
import { CommonEnum } from '@/enum';
import ShowLoading from '@/components/ShowLoading';

export interface IListProps {
  showLoading: boolean;
  comments: Item[];
//   comments: {
//     page: number;
//     pageSize: number;
//     list: Item[];
//   };
}

// Generated by https://quicktype.io

interface Item {
  id: number;
  img: string;
  userId: string;
  userName: string;
  descript: string;
  publishTime: string;
}

// 评论列表
export default function List(props: IListProps) {
  const {
    showLoading,
    comments = [],
  } = props;
  console.log('comments', comments);
  return (
    <div className="comment">
      <h1 className="comment-title">评论</h1>
      <div className="comment-lists">
        {comments.map(item => (
          <div className="comment-lists_item" key={item.id}> 
            <img src={item.img} alt="user" className="avatar" />
            <div className="right">
              <div className="right-top">
                <p>{item.userName}</p>
                <p>{item.publishTime}</p>
              </div>
              <div className="right-bottom">{item.descript}</div>
            </div>
          </div>
        ))}
        <ShowLoading showLoading={showLoading}></ShowLoading>
      </div>
    </div>
  );
}
